export interface TemplateSlot {
  id: string
  type: 'image' | 'text'
  x: number
  y: number
  w: number
  h: number
  content?: string
  fontSize?: number
  fontFamily?: string
  fontWeight?: string
  fontStyle?: string
  textAlign?: string
  letterSpacing?: number
  lineHeight?: number
  textTransform?: string
  borderTop?: boolean
  borderBottom?: boolean
  placeholder?: string
  editable?: boolean
}

export interface NewspaperTemplate {
  id: string
  name: string
  description: string
  category: 'newspaper' | 'magazine' | 'minimal'
  paperSize: 'A4' | 'A3'
  width: number
  height: number
  background: string
  slots: TemplateSlot[]
}

const HEADLINES = [
  'EXTRAORDINARY TIMES',
  'MOMENTS IN HISTORY',
  'THE DAILY CHRONICLE',
  'BREAKING STORIES',
  'FRONT PAGE NEWS',
  'THE EVENING POST',
  'SPECIAL EDITION',
  'WORLD EXCLUSIVE',
]

export function getRandomHeadline(): string {
  return HEADLINES[Math.floor(Math.random() * HEADLINES.length)]!
}

// A4: 210mm x 297mm → at 96dpi roughly 794 x 1123px (we use a scaled representation)
// A3: 297mm x 420mm → at 96dpi roughly 1123 x 1587px

export const templates: NewspaperTemplate[] = [
  // ═══════════════════════════════════════════════════════════
  // TEMPLATE 1: The Daily Chronicle (A4 · 794×1123)
  // ═══════════════════════════════════════════════════════════
  {
    id: 'classic-newspaper-a4',
    name: 'The Daily Chronicle',
    description: 'Classic European newspaper with bold headlines and column layout',
    category: 'newspaper',
    paperSize: 'A4',
    width: 794,
    height: 1123,
    background: '#FAF8F3',
    slots: [
      // ── meta bar ──
      {
        id: 'meta-left',
        type: 'text',
        x: 20,
        y: 8,
        w: 200,
        h: 16,
        content: 'SELF PORTRAIT · PHOTO STUDIO',
        fontSize: 7,
        fontFamily: 'Inter, sans-serif',
        fontWeight: '600',
        textAlign: 'left',
        letterSpacing: 2,
        textTransform: 'uppercase',
        editable: true,
      },
      {
        id: 'meta-center',
        type: 'text',
        x: 220,
        y: 8,
        w: 354,
        h: 16,
        content:
          'Pose, Smile, and Click — Capture Your Mood in Every Scene · Perfect Moments Printed Instantly',
        fontSize: 7,
        fontFamily: 'Inter, sans-serif',
        fontWeight: '400',
        textAlign: 'center',
        letterSpacing: 0.5,
        editable: true,
      },
      {
        id: 'meta-right',
        type: 'text',
        x: 580,
        y: 8,
        w: 194,
        h: 16,
        content: '06.28\n1998',
        fontSize: 10,
        fontFamily: 'Playfair Display, serif',
        fontWeight: '700',
        textAlign: 'right',
        lineHeight: 1,
        editable: true,
      },
      // ── masthead ──
      {
        id: 'masthead',
        type: 'text',
        x: 0,
        y: 28,
        w: 794,
        h: 56,
        content: 'THE DAILY CHRONICLE',
        fontSize: 46,
        fontFamily: 'UnifrakturMaguntia, cursive',
        fontWeight: '400',
        textAlign: 'center',
        letterSpacing: 3,
        borderBottom: true,
        editable: true,
      },
      // ── dateline ──
      {
        id: 'dateline',
        type: 'text',
        x: 0,
        y: 88,
        w: 794,
        h: 22,
        content: "Ad's Road No. 52  ·  Vol. CLXVIII No. 42  ·  WEATHER: SUNNY EVERY DAY",
        fontSize: 8,
        fontFamily: 'Inter, sans-serif',
        fontWeight: '400',
        textAlign: 'center',
        letterSpacing: 2,
        textTransform: 'uppercase',
        borderBottom: true,
        editable: true,
      },
      // ── headline ──
      {
        id: 'headline',
        type: 'text',
        x: 20,
        y: 118,
        w: 754,
        h: 70,
        content: 'WHO WE ARE?\nCapture Your Mood in Every Scene',
        fontSize: 30,
        fontFamily: 'Playfair Display, serif',
        fontWeight: '900',
        textAlign: 'left',
        lineHeight: 1.15,
        editable: true,
      },
      // ── main photo (left) ──
      {
        id: 'photo-main',
        type: 'image',
        x: 20,
        y: 196,
        w: 370,
        h: 350,
        placeholder: 'Main Photo',
      },
      // ── right column: WHO YOU ARE? ──
      {
        id: 'who-label',
        type: 'text',
        x: 402,
        y: 196,
        w: 371,
        h: 28,
        content: 'WHO YOU ARE?',
        fontSize: 20,
        fontFamily: 'Playfair Display, serif',
        fontWeight: '900',
        textAlign: 'left',
        textTransform: 'uppercase',
        editable: true,
      },
      {
        id: 'article-right-top',
        type: 'text',
        x: 402,
        y: 228,
        w: 371,
        h: 196,
        content:
          'You are unique and special, different from everyone else in the world. You can be quiet and gentle, an explorer, a dreamer, a doer.\n\nYour personality is like a light, lighting up the world in your own way. Embrace your fun ideas and let them of your unique possibilities to our private studio. BE PROUD OF BEING YOU.\n\nEvery face tells a story worth capturing. Step into our studio and let the lens reveal the extraordinary within you.',
        fontSize: 10.5,
        fontFamily: 'Lora, serif',
        fontWeight: '400',
        textAlign: 'justify',
        lineHeight: 1.65,
        editable: true,
      },
      // ── right bottom photo ──
      {
        id: 'photo-right',
        type: 'image',
        x: 402,
        y: 430,
        w: 371,
        h: 116,
        placeholder: 'Photo 2',
      },
      // ── section divider ──
      {
        id: 'section-title',
        type: 'text',
        x: 20,
        y: 556,
        w: 754,
        h: 22,
        content: "— TOGETHER, LET'S MAKE MAGIC HAPPEN! —",
        fontSize: 10,
        fontFamily: 'Inter, sans-serif',
        fontWeight: '700',
        textAlign: 'center',
        letterSpacing: 4,
        textTransform: 'uppercase',
        borderTop: true,
        borderBottom: true,
        editable: true,
      },
      // ── bottom row: 2 photos + text ──
      {
        id: 'photo-bl',
        type: 'image',
        x: 20,
        y: 588,
        w: 238,
        h: 210,
        placeholder: 'Photo 3',
      },
      {
        id: 'photo-bm',
        type: 'image',
        x: 268,
        y: 588,
        w: 238,
        h: 210,
        placeholder: 'Photo 4',
      },
      {
        id: 'col3-text',
        type: 'text',
        x: 516,
        y: 588,
        w: 258,
        h: 210,
        content:
          'Every photograph tells the story of a moment suspended in time — a heartbeat, a laugh, a glance. Our studio specialises in capturing the full spectrum of human expression, from the joyful to the contemplative.\n\nBring your ideas, your energy, and your vision. We will bring the light, the equipment, and the expertise to make it unforgettable.',
        fontSize: 10,
        fontFamily: 'Lora, serif',
        fontWeight: '400',
        textAlign: 'justify',
        lineHeight: 1.6,
        editable: true,
      },
      // ── captions ──
      {
        id: 'caption-bl',
        type: 'text',
        x: 20,
        y: 802,
        w: 238,
        h: 16,
        content: 'Fig. I — Our Studio Space',
        fontSize: 8,
        fontFamily: 'Inter, sans-serif',
        fontStyle: 'italic',
        textAlign: 'center',
        editable: true,
      },
      {
        id: 'caption-bm',
        type: 'text',
        x: 268,
        y: 802,
        w: 238,
        h: 16,
        content: 'Fig. II — Behind the Scenes',
        fontSize: 8,
        fontFamily: 'Inter, sans-serif',
        fontStyle: 'italic',
        textAlign: 'center',
        editable: true,
      },
      // ── full-width article section ──
      {
        id: 'article-bottom-label',
        type: 'text',
        x: 20,
        y: 826,
        w: 754,
        h: 18,
        content: 'WHO WE ARE?',
        fontSize: 15,
        fontFamily: 'Playfair Display, serif',
        fontWeight: '900',
        textAlign: 'left',
        borderBottom: true,
        editable: true,
      },
      {
        id: 'article-bottom-col1',
        type: 'text',
        x: 20,
        y: 850,
        w: 370,
        h: 140,
        content:
          'One of a kind SELF PORTRAIT PHOTO STUDIO offering professional photoshoots in just one click! No photographer needed! Starting from choosing one of our unique themed rooms to printing photos, you can enjoy complete privacy and get creative control over your own portrait with our fully automated equipment! Dressing room and makeup area are also available inside the studio for your convenience.',
        fontSize: 10,
        fontFamily: 'Lora, serif',
        fontWeight: '400',
        textAlign: 'justify',
        lineHeight: 1.65,
        editable: true,
      },
      {
        id: 'article-bottom-col2',
        type: 'text',
        x: 404,
        y: 850,
        w: 370,
        h: 140,
        content:
          'Our studio equipment is designed to flatter every face and capture every fleeting emotion. Whether you are shooting for social media, special events, or just for fun, also get some of our exclusive themes available in our studio.\n\nBook your session today — walk-ins welcome. Open daily from 10AM to 10PM. Visit us at the address below or call our hotline number.',
        fontSize: 10,
        fontFamily: 'Lora, serif',
        fontWeight: '400',
        textAlign: 'justify',
        lineHeight: 1.65,
        editable: true,
      },
      // ── sponsor bar ──
      {
        id: 'sponsor-text',
        type: 'text',
        x: 20,
        y: 998,
        w: 754,
        h: 18,
        content: 'POWERED BY  ✦ PRISM STUDIO  ✦  FUJIFILM  ✦  KONICA MINOLTA',
        fontSize: 8,
        fontFamily: 'Inter, sans-serif',
        fontWeight: '600',
        textAlign: 'center',
        letterSpacing: 3,
        textTransform: 'uppercase',
        borderTop: true,
        editable: true,
      },
      // ── bottom banner photo ──
      {
        id: 'photo-bottom',
        type: 'image',
        x: 20,
        y: 1024,
        w: 754,
        h: 68,
        placeholder: 'Banner Photo',
      },
      // ── footer ──
      {
        id: 'footer',
        type: 'text',
        x: 0,
        y: 1096,
        w: 794,
        h: 22,
        content: "Ad's Road No. 52  ·  1998 Shang Hai News Inc.  ·  POWERED BY FUJIFILM",
        fontSize: 7.5,
        fontFamily: 'Inter, sans-serif',
        fontWeight: '400',
        textAlign: 'center',
        letterSpacing: 2,
        textTransform: 'uppercase',
        borderTop: true,
        editable: true,
      },
    ],
  },

  // ═══════════════════════════════════════════════════════════
  // TEMPLATE 2: ETNIABOX Paper (A4 · 794×1123)
  // ═══════════════════════════════════════════════════════════
  {
    id: 'magazine-editorial-a4',
    name: 'ETNIABOX Paper',
    description: 'Bold editorial newspaper with large headline and multi-column article',
    category: 'magazine',
    paperSize: 'A4',
    width: 794,
    height: 1123,
    background: '#FEFEFE',
    slots: [
      // ── top meta bar ──
      {
        id: 'top-meta-left',
        type: 'text',
        x: 20,
        y: 10,
        w: 200,
        h: 16,
        content: 'In a world full of\ntrends, remain a classic',
        fontSize: 7,
        fontFamily: 'Inter, sans-serif',
        fontWeight: '400',
        textAlign: 'left',
        lineHeight: 1.4,
        editable: true,
      },
      {
        id: 'masthead-top',
        type: 'text',
        x: 220,
        y: 8,
        w: 354,
        h: 26,
        content: 'ETNIABOX PAPER',
        fontSize: 22,
        fontFamily: 'Playfair Display, serif',
        fontWeight: '900',
        textAlign: 'center',
        letterSpacing: 3,
        textTransform: 'uppercase',
        editable: true,
      },
      {
        id: 'top-meta-right',
        type: 'text',
        x: 578,
        y: 10,
        w: 196,
        h: 16,
        content: 'Fashion tips:\nstyle remains the same',
        fontSize: 7,
        fontFamily: 'Inter, sans-serif',
        fontWeight: '400',
        textAlign: 'right',
        lineHeight: 1.4,
        editable: true,
      },
      {
        id: 'be-your-own',
        type: 'text',
        x: 0,
        y: 36,
        w: 794,
        h: 18,
        content: 'BE YOUR OWN KIND OF BEAUTIFUL',
        fontSize: 8,
        fontFamily: 'Inter, sans-serif',
        fontWeight: '400',
        textAlign: 'center',
        letterSpacing: 4,
        textTransform: 'uppercase',
        borderBottom: true,
        editable: true,
      },
      // ── big headline ──
      {
        id: 'big-headline',
        type: 'text',
        x: 20,
        y: 60,
        w: 754,
        h: 90,
        content: 'HOW RETRO STYLES\nARE MAKING A MODERN COMEBACK',
        fontSize: 38,
        fontFamily: 'Playfair Display, serif',
        fontWeight: '900',
        textAlign: 'left',
        lineHeight: 1.1,
        editable: true,
      },
      // ── section label ──
      {
        id: 'section-label',
        type: 'text',
        x: 20,
        y: 156,
        w: 400,
        h: 18,
        content: 'The Timeless Appeal of Vintage',
        fontSize: 11,
        fontFamily: 'Playfair Display, serif',
        fontWeight: '700',
        textAlign: 'left',
        borderBottom: true,
        editable: true,
      },
      // ── article left column ──
      {
        id: 'article-col1',
        type: 'text',
        x: 20,
        y: 180,
        w: 230,
        h: 290,
        content:
          "The allure of vintage fashion is timeless, and today it's experiencing a resurgence like never before. From the runways of Paris to the high streets, retro silhouettes are dominating runways and streetwear alike. We explore why the past has made such a compelling, yet natural, comeback into the wardrobes of today's most fashion-forward individuals and the discussions it has sparked.\n\nVintage fashion offers a unique blend of nostalgia and individuality. The rich history behind each piece tells a story and allows the wearer to connect with the past. Fashion enthusiasts are drawn to quality craftsmanship and timeless designs that stand apart from mass-produced fast fashion.",
        fontSize: 10,
        fontFamily: 'Lora, serif',
        fontWeight: '400',
        textAlign: 'justify',
        lineHeight: 1.65,
        editable: true,
      },
      // ── main photo ──
      {
        id: 'photo-main',
        type: 'image',
        x: 262,
        y: 156,
        w: 512,
        h: 314,
        placeholder: 'Main Photo',
      },
      // ── pull quote ──
      {
        id: 'pull-quote',
        type: 'text',
        x: 20,
        y: 478,
        w: 754,
        h: 26,
        content: 'The vintage trend aligns with the growing emphasis on sustainability.',
        fontSize: 12,
        fontFamily: 'Lora, serif',
        fontStyle: 'italic',
        fontWeight: '700',
        textAlign: 'left',
        borderTop: true,
        borderBottom: true,
        editable: true,
      },
      // ── three bottom photos ──
      {
        id: 'photo-b1',
        type: 'image',
        x: 20,
        y: 512,
        w: 240,
        h: 220,
        placeholder: 'Photo 2',
      },
      {
        id: 'photo-b2',
        type: 'image',
        x: 270,
        y: 512,
        w: 240,
        h: 220,
        placeholder: 'Photo 3',
      },
      {
        id: 'photo-b3',
        type: 'image',
        x: 520,
        y: 512,
        w: 254,
        h: 220,
        placeholder: 'Photo 4',
      },
      // ── photo captions ──
      {
        id: 'caption-b1',
        type: 'text',
        x: 20,
        y: 736,
        w: 240,
        h: 16,
        content: 'Fig. I — Classic Retro Style',
        fontSize: 8,
        fontFamily: 'Inter, sans-serif',
        fontStyle: 'italic',
        textAlign: 'center',
        editable: true,
      },
      {
        id: 'caption-b2',
        type: 'text',
        x: 270,
        y: 736,
        w: 240,
        h: 16,
        content: 'Fig. II — Modern Vintage',
        fontSize: 8,
        fontFamily: 'Inter, sans-serif',
        fontStyle: 'italic',
        textAlign: 'center',
        editable: true,
      },
      {
        id: 'caption-b3',
        type: 'text',
        x: 520,
        y: 736,
        w: 254,
        h: 16,
        content: 'Fig. III — Timeless Elegance',
        fontSize: 8,
        fontFamily: 'Inter, sans-serif',
        fontStyle: 'italic',
        textAlign: 'center',
        editable: true,
      },
      // ── two-column article ──
      {
        id: 'article-mid-col1',
        type: 'text',
        x: 20,
        y: 762,
        w: 365,
        h: 190,
        content:
          "By choosing secondhand and vintage pieces, consumers reduce waste and support a more environmentally responsible approach to fashion. It's a philosophy that resonates with a generation that recognizes the importance of conscious consumerism.\n\nMixing vintage with contemporary pieces is the key to creating a balanced wardrobe. It allows you to express your unique identity while staying true to a retro aesthetic. The pairing of a vintage blazer with modern jeans creates a harmonious blend that feels both fresh and personal.",
        fontSize: 10,
        fontFamily: 'Lora, serif',
        fontWeight: '400',
        textAlign: 'justify',
        lineHeight: 1.65,
        editable: true,
      },
      {
        id: 'article-mid-col2',
        type: 'text',
        x: 397,
        y: 762,
        w: 377,
        h: 190,
        content:
          'Icons Leading the Trend Like Audrey, and Yves Saint Laurent, have frequently cited vintage aesthetics as a major source of their own enthusiasm to embrace creative styles in clothing. Their influence on millions of fans worldwide and their massive media posts have sparked a renewed interest in Vintage wear.\n\nThe rise of online platforms dedicated to vintage fashion has made it easier than ever to access unique, high-quality pieces from around the world. Curated collections and expert resellers are bringing forgotten treasures back to life for a new generation of style enthusiasts.',
        fontSize: 10,
        fontFamily: 'Lora, serif',
        fontWeight: '400',
        textAlign: 'justify',
        lineHeight: 1.65,
        editable: true,
      },
      // ── wide bottom photo ──
      {
        id: 'photo-bottom',
        type: 'image',
        x: 20,
        y: 962,
        w: 754,
        h: 112,
        placeholder: 'Wide Photo',
      },
      // ── footer ──
      {
        id: 'footer',
        type: 'text',
        x: 0,
        y: 1094,
        w: 794,
        h: 22,
        content: 'ETNIABOX PAPER · BE YOUR OWN KIND OF BEAUTIFUL · VOL. I · 2024',
        fontSize: 7.5,
        fontFamily: 'Inter, sans-serif',
        fontWeight: '400',
        textAlign: 'center',
        letterSpacing: 2,
        textTransform: 'uppercase',
        borderTop: true,
        editable: true,
      },
    ],
  },

  // ═══════════════════════════════════════════════════════════
  // TEMPLATE 3: Madefannie House (A4 · 794×1123)
  // ═══════════════════════════════════════════════════════════
  {
    id: 'minimal-retro-a4',
    name: 'Madefannie House',
    description: 'Mixed typography newspaper with large editorial headline and photo grid',
    category: 'minimal',
    paperSize: 'A4',
    width: 794,
    height: 1123,
    background: '#FAF8F3',
    slots: [
      // ── masthead row ──
      {
        id: 'masthead-left',
        type: 'text',
        x: 20,
        y: 14,
        w: 60,
        h: 28,
        content: 'Mᶜ\n1957',
        fontSize: 8,
        fontFamily: 'Inter, sans-serif',
        fontWeight: '400',
        textAlign: 'left',
        lineHeight: 1.3,
        editable: true,
      },
      {
        id: 'masthead-main',
        type: 'text',
        x: 84,
        y: 10,
        w: 500,
        h: 38,
        content: 'MADEFANNIE HOUSE',
        fontSize: 34,
        fontFamily: 'Playfair Display, serif',
        fontWeight: '900',
        textAlign: 'left',
        letterSpacing: 2,
        textTransform: 'uppercase',
        editable: true,
      },
      {
        id: 'masthead-right',
        type: 'text',
        x: 690,
        y: 14,
        w: 84,
        h: 28,
        content: 'Fᶠ\nFashion',
        fontSize: 8,
        fontFamily: 'Inter, sans-serif',
        fontWeight: '400',
        textAlign: 'right',
        lineHeight: 1.3,
        editable: true,
      },
      // ── dateline ──
      {
        id: 'dateline',
        type: 'text',
        x: 0,
        y: 52,
        w: 794,
        h: 18,
        content: 'Mcfly No. 33  ·  QUARTERLY EDITION  ·  est. 1957  ·  Ephes 4:7',
        fontSize: 7.5,
        fontFamily: 'Inter, sans-serif',
        fontWeight: '400',
        textAlign: 'center',
        letterSpacing: 2,
        textTransform: 'uppercase',
        borderTop: true,
        borderBottom: true,
        editable: true,
      },
      // ── mixed headline area ──
      {
        id: 'headline-line1',
        type: 'text',
        x: 20,
        y: 78,
        w: 340,
        h: 28,
        content: 'Cofffe* Baguette *Cheese* Love',
        fontSize: 16,
        fontFamily: 'Lora, serif',
        fontStyle: 'italic',
        fontWeight: '400',
        textAlign: 'left',
        editable: true,
      },
      {
        id: 'headline-paris',
        type: 'text',
        x: 364,
        y: 72,
        w: 410,
        h: 40,
        content: 'Paris',
        fontSize: 44,
        fontFamily: 'Playfair Display, serif',
        fontWeight: '900',
        fontStyle: 'italic',
        textAlign: 'right',
        editable: true,
      },
      // ── Find section ──
      {
        id: 'find-label',
        type: 'text',
        x: 20,
        y: 118,
        w: 60,
        h: 22,
        content: 'Find',
        fontSize: 18,
        fontFamily: 'Playfair Display, serif',
        fontWeight: '900',
        fontStyle: 'italic',
        textAlign: 'left',
        editable: true,
      },
      {
        id: 'article-col1',
        type: 'text',
        x: 84,
        y: 118,
        w: 330,
        h: 200,
        content:
          'La découverte des destinations commencées par la trouille, et un engagement de soi commence. Voici les quelques petites choses pour vous connaître vous-même, comment vous y préparer, et en faire de belles occasions et de vous faire plaisir et ce que vous faites. Pour commencer, pensez à quelques-uns de vos amis talentué et ce que vous trouvez bien. Sans prise de conscience, le changement extérieur pour aller vers le meilleur de soi et de quitter sa "expérience de soi".',
        fontSize: 10,
        fontFamily: 'Lora, serif',
        fontWeight: '400',
        textAlign: 'justify',
        lineHeight: 1.65,
        editable: true,
      },
      {
        id: 'article-col2',
        type: 'text',
        x: 426,
        y: 118,
        w: 348,
        h: 200,
        content:
          "soit en présence ou à travers des photos, des mots ou des expériences. Votre déclaration qui cache de la vie quotidienne sera votre premier témoignage de singularité. Maintenant, soyez-vous très clair en vous concentrant sur ce que vous êtes profondément. Il y a plein d'autres façons de vous affirmer et choisir! D'une part, c'est la conviction. D'autre part, le monde a besoin de votre vitalité. Chacun de nous a des qualités particulières qui font avancer le monde que quelques-uns.",
        fontSize: 10,
        fontFamily: 'Lora, serif',
        fontWeight: '400',
        textAlign: 'justify',
        lineHeight: 1.65,
        editable: true,
      },
      // ── three photos row ──
      {
        id: 'photo-1',
        type: 'image',
        x: 20,
        y: 328,
        w: 238,
        h: 220,
        placeholder: 'Photo 1',
      },
      {
        id: 'photo-2',
        type: 'image',
        x: 268,
        y: 328,
        w: 238,
        h: 220,
        placeholder: 'Photo 2',
      },
      {
        id: 'photo-3',
        type: 'image',
        x: 516,
        y: 328,
        w: 258,
        h: 220,
        placeholder: 'Photo 3',
      },
      // ── divider ──
      {
        id: 'bottom-divider',
        type: 'text',
        x: 20,
        y: 556,
        w: 754,
        h: 18,
        content: '────────────────────────────────────────────────────────────────────────',
        fontSize: 8,
        fontFamily: 'Inter, sans-serif',
        fontWeight: '400',
        textAlign: 'center',
        borderBottom: true,
        editable: false,
      },
      // ── Cook section ──
      {
        id: 'cook-label',
        type: 'text',
        x: 20,
        y: 582,
        w: 60,
        h: 22,
        content: 'Cook',
        fontSize: 18,
        fontFamily: 'Playfair Display, serif',
        fontWeight: '900',
        fontStyle: 'italic',
        textAlign: 'left',
        editable: true,
      },
      {
        id: 'article-btm-col1',
        type: 'text',
        x: 84,
        y: 582,
        w: 330,
        h: 200,
        content:
          "Maintenant, si vous trouvez les grandes dites que chacun d'entre nous a, vous allez les reconnaître dans les choses subtiles avec de la sensibilité.\n\nAu fond de chaque être et l'imagination se pratique: les pensées que la difficulté a trouvée.\n\nL'imagination que si vous êtes conclus à faire des idées et l'imaginer. Si étudié, développé ou aidé à faire aller des autres le plus loin possible, si vous arrivez à quelque lieu à quelques étapes.",
        fontSize: 10,
        fontFamily: 'Lora, serif',
        fontWeight: '400',
        textAlign: 'justify',
        lineHeight: 1.65,
        editable: true,
      },
      {
        id: 'bonjour-label',
        type: 'text',
        x: 426,
        y: 574,
        w: 348,
        h: 50,
        content: 'Bonjour!',
        fontSize: 40,
        fontFamily: 'Playfair Display, serif',
        fontWeight: '900',
        fontStyle: 'italic',
        textAlign: 'right',
        editable: true,
      },
      {
        id: 'article-btm-col2',
        type: 'text',
        x: 426,
        y: 628,
        w: 348,
        h: 154,
        content:
          "Quelqu'un d'autre doit aimer les ingrédients les plus simples de la vie. Voici quelques idées qui feront que vos vies ne peuvent pas aimer tous les ingrédients. On peut faire des plats plus beau et plus délicieux avec les meilleurs ingrédients. On peut réaliser les ingrédients qu'on a pas à Madefannie house, voici quelques-uns d'entre eux en société.",
        fontSize: 10,
        fontFamily: 'Lora, serif',
        fontWeight: '400',
        textAlign: 'justify',
        lineHeight: 1.65,
        editable: true,
      },
      // ── Share + photo ──
      {
        id: 'share-label',
        type: 'text',
        x: 20,
        y: 792,
        w: 754,
        h: 24,
        content: 'Share',
        fontSize: 20,
        fontFamily: 'Playfair Display, serif',
        fontWeight: '700',
        fontStyle: 'italic',
        textAlign: 'left',
        borderTop: true,
        editable: true,
      },
      {
        id: 'photo-4',
        type: 'image',
        x: 20,
        y: 824,
        w: 754,
        h: 268,
        placeholder: 'Photo 4',
      },
      // ── footer ──
      {
        id: 'footer',
        type: 'text',
        x: 0,
        y: 1098,
        w: 794,
        h: 22,
        content: 'MADEFANNIE  ·  QUARTERLY EDITION  ·  Ephes 4:7',
        fontSize: 8,
        fontFamily: 'Inter, sans-serif',
        fontWeight: '400',
        textAlign: 'center',
        letterSpacing: 3,
        textTransform: 'uppercase',
        borderTop: true,
        editable: true,
      },
    ],
  },

  // ═══════════════════════════════════════════════════════════
  // TEMPLATE 4: The Grand Gazette (A3 · 1123×1587)
  // ═══════════════════════════════════════════════════════════
  {
    id: 'classic-newspaper-a3',
    name: 'The Grand Gazette',
    description: 'Large format broadsheet newspaper with multi-column layout',
    category: 'newspaper',
    paperSize: 'A3',
    width: 1123,
    height: 1587,
    background: '#FAF8F3',
    slots: [
      // ── meta bar ──
      {
        id: 'meta-left',
        type: 'text',
        x: 30,
        y: 10,
        w: 300,
        h: 16,
        content: 'SELF PORTRAIT · GRAND PHOTO STUDIO',
        fontSize: 8,
        fontFamily: 'Inter, sans-serif',
        fontWeight: '600',
        textAlign: 'left',
        letterSpacing: 2,
        textTransform: 'uppercase',
        editable: true,
      },
      {
        id: 'meta-center',
        type: 'text',
        x: 334,
        y: 10,
        w: 455,
        h: 16,
        content:
          'Pose, Smile, and Click — Capture Your Mood in Every Scene · Perfect Moments Printed Instantly',
        fontSize: 7.5,
        fontFamily: 'Inter, sans-serif',
        fontWeight: '400',
        textAlign: 'center',
        letterSpacing: 0.5,
        editable: true,
      },
      {
        id: 'meta-right',
        type: 'text',
        x: 793,
        y: 10,
        w: 300,
        h: 16,
        content: '06.28 · 1998',
        fontSize: 9,
        fontFamily: 'Playfair Display, serif',
        fontWeight: '700',
        textAlign: 'right',
        editable: true,
      },
      // ── masthead ──
      {
        id: 'masthead',
        type: 'text',
        x: 0,
        y: 28,
        w: 1123,
        h: 72,
        content: 'THE GRAND GAZETTE',
        fontSize: 62,
        fontFamily: 'UnifrakturMaguntia, cursive',
        fontWeight: '400',
        textAlign: 'center',
        letterSpacing: 6,
        borderBottom: true,
        editable: true,
      },
      // ── dateline ──
      {
        id: 'dateline',
        type: 'text',
        x: 0,
        y: 102,
        w: 1123,
        h: 24,
        content:
          'Vol. CCXII — No. 1  ·  ESTABLISHED 1823  ·  LONDON, ENGLAND  ·  PRICE: THREE PENCE  ·  WEATHER: FAIR & MILD',
        fontSize: 9,
        fontFamily: 'Inter, sans-serif',
        fontWeight: '400',
        textAlign: 'center',
        letterSpacing: 3,
        textTransform: 'uppercase',
        borderBottom: true,
        editable: true,
      },
      // ── headline ──
      {
        id: 'headline',
        type: 'text',
        x: 30,
        y: 134,
        w: 1063,
        h: 86,
        content: 'REMARKABLE SCENES CAPTURED IN STUNNING\nPHOTOGRAPHIC EXHIBITION OF THE SEASON',
        fontSize: 46,
        fontFamily: 'Playfair Display, serif',
        fontWeight: '900',
        textAlign: 'center',
        lineHeight: 1.1,
        textTransform: 'uppercase',
        editable: true,
      },
      // ── subtitle ──
      {
        id: 'subtitle',
        type: 'text',
        x: 150,
        y: 228,
        w: 823,
        h: 26,
        content:
          'Our Special Correspondent Reports on the Most Anticipated Cultural Event of the Season — A Spectacular Display of Vision and Craft',
        fontSize: 13,
        fontFamily: 'Lora, serif',
        fontStyle: 'italic',
        fontWeight: '400',
        textAlign: 'center',
        borderBottom: true,
        editable: true,
      },
      // ── byline ──
      {
        id: 'byline',
        type: 'text',
        x: 30,
        y: 262,
        w: 500,
        h: 18,
        content: 'By Our Chief Correspondent · Photography by Studio',
        fontSize: 9,
        fontFamily: 'Inter, sans-serif',
        fontWeight: '400',
        textAlign: 'left',
        letterSpacing: 1,
        textTransform: 'uppercase',
        editable: true,
      },
      {
        id: 'byline-date',
        type: 'text',
        x: 630,
        y: 262,
        w: 463,
        h: 18,
        content: 'PUBLISHED: MONDAY, 28TH JUNE 1998',
        fontSize: 9,
        fontFamily: 'Inter, sans-serif',
        fontWeight: '400',
        textAlign: 'right',
        letterSpacing: 1,
        textTransform: 'uppercase',
        editable: true,
      },
      // ── main photo ──
      {
        id: 'photo-main',
        type: 'image',
        x: 30,
        y: 286,
        w: 660,
        h: 460,
        placeholder: 'Main Photo',
      },
      // ── right column ──
      {
        id: 'article-right-t',
        type: 'text',
        x: 706,
        y: 286,
        w: 387,
        h: 26,
        content: 'OPENING STATEMENT',
        fontSize: 10,
        fontFamily: 'Inter, sans-serif',
        fontWeight: '700',
        textAlign: 'left',
        letterSpacing: 3,
        textTransform: 'uppercase',
        borderBottom: true,
        editable: true,
      },
      {
        id: 'article-right',
        type: 'text',
        x: 706,
        y: 318,
        w: 387,
        h: 428,
        content:
          'The exhibition, which opened its doors to a captivated public yesterday morning, has been described by critics as nothing short of revolutionary in scope and ambition.\n\nVisitors from across the continent have gathered to witness what many are calling the defining photographic collection of our generation — a body of work that challenges conventional notions of portraiture and documentary photography.\n\n"The images speak with a clarity and emotional depth that is truly rare," noted the distinguished art critic of The Times. "Each frame feels like a window into another world, yet simultaneously holds up a mirror to our own."\n\nThe collection spans a remarkable range of subjects, from intimate close-up portraits to sweeping panoramic landscapes, each rendered with extraordinary attention to detail and composition.\n\nThe photographer spent three years traveling across twelve countries to assemble this definitive collection, working in natural light conditions and using only traditional darkroom techniques to achieve the final prints.\n\nPerhaps most remarkable is the consistency of vision throughout — a quiet, contemplative quality that invites the viewer to pause and truly look.',
        fontSize: 12,
        fontFamily: 'Lora, serif',
        fontWeight: '400',
        textAlign: 'justify',
        lineHeight: 1.65,
        editable: true,
      },
      // ── section divider ──
      {
        id: 'section-div',
        type: 'text',
        x: 30,
        y: 760,
        w: 1063,
        h: 26,
        content: '— GALLERY OF NOTABLE PHOTOGRAPHS FROM THE COLLECTION —',
        fontSize: 11,
        fontFamily: 'Inter, sans-serif',
        fontWeight: '700',
        textAlign: 'center',
        letterSpacing: 5,
        textTransform: 'uppercase',
        borderTop: true,
        borderBottom: true,
        editable: true,
      },
      // ── row of 4 photos ──
      {
        id: 'photo-2',
        type: 'image',
        x: 30,
        y: 794,
        w: 252,
        h: 230,
        placeholder: 'Photo 2',
      },
      {
        id: 'photo-3',
        type: 'image',
        x: 294,
        y: 794,
        w: 252,
        h: 230,
        placeholder: 'Photo 3',
      },
      {
        id: 'photo-4',
        type: 'image',
        x: 558,
        y: 794,
        w: 252,
        h: 230,
        placeholder: 'Photo 4',
      },
      {
        id: 'photo-5',
        type: 'image',
        x: 822,
        y: 794,
        w: 271,
        h: 230,
        placeholder: 'Photo 5',
      },
      // ── captions ──
      {
        id: 'cap-2',
        type: 'text',
        x: 30,
        y: 1028,
        w: 252,
        h: 18,
        content: 'Plate I — A Study in Contrast',
        fontSize: 9,
        fontFamily: 'Inter, sans-serif',
        fontStyle: 'italic',
        textAlign: 'center',
        editable: true,
      },
      {
        id: 'cap-3',
        type: 'text',
        x: 294,
        y: 1028,
        w: 252,
        h: 18,
        content: 'Plate II — Morning Light',
        fontSize: 9,
        fontFamily: 'Inter, sans-serif',
        fontStyle: 'italic',
        textAlign: 'center',
        editable: true,
      },
      {
        id: 'cap-4',
        type: 'text',
        x: 558,
        y: 1028,
        w: 252,
        h: 18,
        content: 'Plate III — The Decisive Moment',
        fontSize: 9,
        fontFamily: 'Inter, sans-serif',
        fontStyle: 'italic',
        textAlign: 'center',
        editable: true,
      },
      {
        id: 'cap-5',
        type: 'text',
        x: 822,
        y: 1028,
        w: 271,
        h: 18,
        content: 'Plate IV — Reflections',
        fontSize: 9,
        fontFamily: 'Inter, sans-serif',
        fontStyle: 'italic',
        textAlign: 'center',
        editable: true,
      },
      // ── section labels ──
      {
        id: 'section2-label',
        type: 'text',
        x: 30,
        y: 1054,
        w: 530,
        h: 20,
        content: 'CRITICAL RESPONSE',
        fontSize: 10,
        fontFamily: 'Inter, sans-serif',
        fontWeight: '700',
        textAlign: 'left',
        letterSpacing: 3,
        textTransform: 'uppercase',
        borderBottom: true,
        editable: true,
      },
      {
        id: 'section2-label-r',
        type: 'text',
        x: 580,
        y: 1054,
        w: 513,
        h: 20,
        content: 'EXHIBITION DETAILS',
        fontSize: 10,
        fontFamily: 'Inter, sans-serif',
        fontWeight: '700',
        textAlign: 'left',
        letterSpacing: 3,
        textTransform: 'uppercase',
        borderBottom: true,
        editable: true,
      },
      // ── bottom two columns ──
      {
        id: 'bottom-col-left',
        type: 'text',
        x: 30,
        y: 1080,
        w: 530,
        h: 140,
        content:
          'The curator, speaking at the opening reception, emphasized the importance of preserving photographic heritage in an age of rapid technological change. "These images represent not merely artistic achievement, but a vital record of our shared human experience," she remarked to an audience of distinguished guests and fellow artists.\n\n"What strikes me most about this collection is its humanity," wrote one prominent critic. "The photographer has an uncanny ability to find the universal within the deeply personal, to make us feel as though we are seeing ourselves reflected in the faces of strangers."',
        fontSize: 11,
        fontFamily: 'Lora, serif',
        fontWeight: '400',
        textAlign: 'justify',
        lineHeight: 1.65,
        editable: true,
      },
      {
        id: 'bottom-col-right',
        type: 'text',
        x: 580,
        y: 1080,
        w: 513,
        h: 140,
        content:
          'The exhibition will remain open to the public through the end of the season. Tickets may be obtained at the gallery entrance or through advance booking at the official website.\n\nSpecial guided tours are available every Saturday and Sunday, offering visitors an intimate exploration of the collection with expert commentary.\n\nOpening hours: Tuesday — Sunday, 10:00 to 19:00. Last admission at 18:30. The gallery is closed on Mondays. Group bookings available for parties of ten or more. All proceeds support emerging photographic talent.',
        fontSize: 11,
        fontFamily: 'Lora, serif',
        fontWeight: '400',
        textAlign: 'justify',
        lineHeight: 1.65,
        editable: true,
      },
      // ── bottom photos ──
      {
        id: 'photo-6',
        type: 'image',
        x: 30,
        y: 1232,
        w: 530,
        h: 290,
        placeholder: 'Photo 6',
      },
      {
        id: 'photo-7',
        type: 'image',
        x: 580,
        y: 1232,
        w: 513,
        h: 290,
        placeholder: 'Photo 7',
      },
      // ── footer ──
      {
        id: 'footer',
        type: 'text',
        x: 0,
        y: 1548,
        w: 1123,
        h: 24,
        content:
          '© THE GRAND GAZETTE · ALL RIGHTS RESERVED · ESTABLISHED 1823 · PRINTED IN LONDON, ENGLAND',
        fontSize: 8,
        fontFamily: 'Inter, sans-serif',
        fontWeight: '400',
        textAlign: 'center',
        letterSpacing: 3,
        textTransform: 'uppercase',
        borderTop: true,
        editable: true,
      },
    ],
  },

  // ═══════════════════════════════════════════════════════════
  // TEMPLATE 5: Grand Madefannie (A3 · 1123×1587)
  // ═══════════════════════════════════════════════════════════
  {
    id: 'magazine-editorial-a3',
    name: 'Grand Madefannie',
    description: 'Large format mixed editorial with bold typography and photo grid',
    category: 'magazine',
    paperSize: 'A3',
    width: 1123,
    height: 1587,
    background: '#FAF8F3',
    slots: [
      // ── masthead row ──
      {
        id: 'masthead-left',
        type: 'text',
        x: 30,
        y: 16,
        w: 70,
        h: 32,
        content: 'Mᶜ\n1957',
        fontSize: 9,
        fontFamily: 'Inter, sans-serif',
        fontWeight: '400',
        textAlign: 'left',
        lineHeight: 1.3,
        editable: true,
      },
      {
        id: 'masthead-main',
        type: 'text',
        x: 110,
        y: 12,
        w: 700,
        h: 46,
        content: 'MADEFANNIE HOUSE',
        fontSize: 46,
        fontFamily: 'Playfair Display, serif',
        fontWeight: '900',
        textAlign: 'left',
        letterSpacing: 3,
        textTransform: 'uppercase',
        editable: true,
      },
      {
        id: 'masthead-right',
        type: 'text',
        x: 1010,
        y: 16,
        w: 83,
        h: 32,
        content: 'Fᶠ\nFashion',
        fontSize: 9,
        fontFamily: 'Inter, sans-serif',
        fontWeight: '400',
        textAlign: 'right',
        lineHeight: 1.3,
        editable: true,
      },
      // ── dateline ──
      {
        id: 'dateline',
        type: 'text',
        x: 0,
        y: 60,
        w: 1123,
        h: 22,
        content: 'Mcfly No. 33  ·  QUARTERLY GRAND EDITION  ·  ESTABLISHED 1957  ·  Ephes 4:7',
        fontSize: 8,
        fontFamily: 'Inter, sans-serif',
        fontWeight: '400',
        textAlign: 'center',
        letterSpacing: 2,
        textTransform: 'uppercase',
        borderTop: true,
        borderBottom: true,
        editable: true,
      },
      // ── mixed headline ──
      {
        id: 'headline-line1',
        type: 'text',
        x: 30,
        y: 92,
        w: 540,
        h: 34,
        content: 'Coffee* Baguette *Cheese* Love',
        fontSize: 22,
        fontFamily: 'Lora, serif',
        fontStyle: 'italic',
        fontWeight: '400',
        textAlign: 'left',
        editable: true,
      },
      {
        id: 'headline-paris',
        type: 'text',
        x: 574,
        y: 82,
        w: 519,
        h: 54,
        content: 'Paris',
        fontSize: 58,
        fontFamily: 'Playfair Display, serif',
        fontWeight: '900',
        fontStyle: 'italic',
        textAlign: 'right',
        editable: true,
      },
      // ── Find section ──
      {
        id: 'find-label',
        type: 'text',
        x: 30,
        y: 142,
        w: 80,
        h: 28,
        content: 'Find',
        fontSize: 24,
        fontFamily: 'Playfair Display, serif',
        fontWeight: '900',
        fontStyle: 'italic',
        textAlign: 'left',
        editable: true,
      },
      {
        id: 'article-col1',
        type: 'text',
        x: 120,
        y: 142,
        w: 460,
        h: 230,
        content:
          'La découverte des destinations commencées par la trouille, et un engagement de soi commence. Voici les quelques petites choses pour vous connaître vous-même, comment vous y préparer, et en faire de belles occasions et de vous faire plaisir et ce que vous faites. Pour commencer, pensez à quelques-uns de vos amis talentués et ce que vous trouvez bien. Sans prise de conscience, le changement extérieur pour aller vers le meilleur de soi et de quitter sa "expérience de soi".\n\nLa mode est un langage, et chaque vêtement que vous portez raconte une histoire. Choisissez des pièces qui parlent de votre âme, de vos voyages, de vos rêves. Car la vraie élégance ne vient pas d\'une étiquette mais d\'une attitude.',
        fontSize: 11,
        fontFamily: 'Lora, serif',
        fontWeight: '400',
        textAlign: 'justify',
        lineHeight: 1.65,
        editable: true,
      },
      {
        id: 'article-col2',
        type: 'text',
        x: 600,
        y: 142,
        w: 493,
        h: 230,
        content:
          "soit en présence ou à travers des photos, des mots ou des expériences. Votre déclaration qui cache de la vie quotidienne sera votre premier témoignage de singularité. Maintenant, soyez-vous très clair en vous concentrant sur ce que vous êtes profondément. Il y a plein d'autres façons de vous affirmer et choisir!\n\nD'une part, c'est la conviction. D'autre part, le monde a besoin de votre vitalité. Chacun de nous a des qualités particulières qui font avancer le monde. Embrassez votre unicité, cultivez votre style et partagez votre lumière avec ceux qui vous entourent. Vous êtes votre meilleur atout.",
        fontSize: 11,
        fontFamily: 'Lora, serif',
        fontWeight: '400',
        textAlign: 'justify',
        lineHeight: 1.65,
        editable: true,
      },
      // ── three photos ──
      {
        id: 'photo-1',
        type: 'image',
        x: 30,
        y: 384,
        w: 350,
        h: 280,
        placeholder: 'Photo 1',
      },
      {
        id: 'photo-2',
        type: 'image',
        x: 392,
        y: 384,
        w: 350,
        h: 280,
        placeholder: 'Photo 2',
      },
      {
        id: 'photo-3',
        type: 'image',
        x: 754,
        y: 384,
        w: 339,
        h: 280,
        placeholder: 'Photo 3',
      },
      // ── divider ──
      {
        id: 'section-divider',
        type: 'text',
        x: 30,
        y: 672,
        w: 1063,
        h: 22,
        content:
          '────────────────────────────────────────────────────────────────────────────────────────────────',
        fontSize: 8,
        fontFamily: 'Inter, sans-serif',
        fontWeight: '400',
        textAlign: 'center',
        borderBottom: true,
        editable: false,
      },
      // ── Cook section ──
      {
        id: 'cook-label',
        type: 'text',
        x: 30,
        y: 706,
        w: 80,
        h: 28,
        content: 'Cook',
        fontSize: 24,
        fontFamily: 'Playfair Display, serif',
        fontWeight: '900',
        fontStyle: 'italic',
        textAlign: 'left',
        editable: true,
      },
      {
        id: 'article-btm-col1',
        type: 'text',
        x: 120,
        y: 706,
        w: 460,
        h: 230,
        content:
          "Maintenant, si vous trouvez les grandes dites que chacun d'entre nous a, vous allez les reconnaître dans les choses subtiles avec de la sensibilité.\n\nAu fond de chaque être et l'imagination se pratique: les pensées que la difficulté a trouvée. L'imagination que si vous êtes conclus à faire des idées et l'imaginer. Si étudié, développé ou aidé à faire aller des autres le plus loin possible, si vous arrivez à quelque lieu à quelques étapes si vous arrêtez.\n\nLa cuisine, comme la vie, se savoure lentement. Chaque plat est une histoire d'amour entre les ingrédients, une danse de saveurs qui transporte l'âme. Madefannie house vous invite à la table de l'existence.",
        fontSize: 11,
        fontFamily: 'Lora, serif',
        fontWeight: '400',
        textAlign: 'justify',
        lineHeight: 1.65,
        editable: true,
      },
      {
        id: 'bonjour-label',
        type: 'text',
        x: 600,
        y: 696,
        w: 493,
        h: 58,
        content: 'Bonjour!',
        fontSize: 52,
        fontFamily: 'Playfair Display, serif',
        fontWeight: '900',
        fontStyle: 'italic',
        textAlign: 'right',
        editable: true,
      },
      {
        id: 'article-btm-col2',
        type: 'text',
        x: 600,
        y: 760,
        w: 493,
        h: 176,
        content:
          "Quelqu'un d'autre doit aimer les ingrédients les plus simples de la vie. Voici quelques idées qui feront que vos vies ne peuvent pas aimer tous les ingrédients. On peut faire des plats plus beau et plus délicieux avec les meilleurs ingrédients.\n\nOn peut réaliser les ingrédients qu'on a pas à Madefannie house, voici quelques-uns d'entre eux en société. Nous pouvons vous aider a aider les autres et nous réjouir d'une telle magnifique existence ensemble. La joie est un ingrédient universel.",
        fontSize: 11,
        fontFamily: 'Lora, serif',
        fontWeight: '400',
        textAlign: 'justify',
        lineHeight: 1.65,
        editable: true,
      },
      // ── Share section ──
      {
        id: 'share-label',
        type: 'text',
        x: 30,
        y: 948,
        w: 1063,
        h: 28,
        content: 'Share',
        fontSize: 24,
        fontFamily: 'Playfair Display, serif',
        fontWeight: '700',
        fontStyle: 'italic',
        textAlign: 'left',
        borderTop: true,
        editable: true,
      },
      // ── photo grid ──
      {
        id: 'photo-4',
        type: 'image',
        x: 30,
        y: 986,
        w: 525,
        h: 340,
        placeholder: 'Photo 4',
      },
      {
        id: 'photo-5',
        type: 'image',
        x: 568,
        y: 986,
        w: 525,
        h: 340,
        placeholder: 'Photo 5',
      },
      {
        id: 'photo-6',
        type: 'image',
        x: 30,
        y: 1340,
        w: 344,
        h: 200,
        placeholder: 'Photo 6',
      },
      {
        id: 'photo-7',
        type: 'image',
        x: 386,
        y: 1340,
        w: 344,
        h: 200,
        placeholder: 'Photo 7',
      },
      {
        id: 'photo-8',
        type: 'image',
        x: 742,
        y: 1340,
        w: 351,
        h: 200,
        placeholder: 'Photo 8',
      },
      // ── footer ──
      {
        id: 'footer',
        type: 'text',
        x: 0,
        y: 1555,
        w: 1123,
        h: 22,
        content: 'MADEFANNIE  ·  QUARTERLY GRAND EDITION  ·  ESTABLISHED 1957  ·  Ephes 4:7',
        fontSize: 8,
        fontFamily: 'Inter, sans-serif',
        fontWeight: '400',
        textAlign: 'center',
        letterSpacing: 3,
        textTransform: 'uppercase',
        borderTop: true,
        editable: true,
      },
    ],
  },

  // ═══════════════════════════════════════════════════════════
  // TEMPLATE 6: The Evening Herald (A4 · 794×1123) — NEW
  // ═══════════════════════════════════════════════════════════
  {
    id: 'evening-herald-a4',
    name: 'The Evening Herald',
    description: 'Symmetric broadsheet front page with ornate header and 3-column layout',
    category: 'newspaper',
    paperSize: 'A4',
    width: 794,
    height: 1123,
    background: '#FAF8F3',
    slots: [
      // ── ornamental header ──
      {
        id: 'ornament-top',
        type: 'text',
        x: 0,
        y: 6,
        w: 794,
        h: 14,
        content: '✦ ─────────── ✦ ─────────── ✦ ─────────── ✦ ─────────── ✦',
        fontSize: 8,
        fontFamily: 'Inter, sans-serif',
        fontWeight: '400',
        textAlign: 'center',
        letterSpacing: 1,
        editable: false,
      },
      {
        id: 'masthead',
        type: 'text',
        x: 0,
        y: 22,
        w: 794,
        h: 50,
        content: 'THE EVENING HERALD',
        fontSize: 42,
        fontFamily: 'UnifrakturMaguntia, cursive',
        fontWeight: '400',
        textAlign: 'center',
        letterSpacing: 4,
        editable: true,
      },
      {
        id: 'dateline',
        type: 'text',
        x: 0,
        y: 76,
        w: 794,
        h: 22,
        content: 'LONDON · WEDNESDAY, 15TH MARCH 2026 · EVENING EDITION · PRICE: TWO PENCE',
        fontSize: 8,
        fontFamily: 'Inter, sans-serif',
        fontWeight: '400',
        textAlign: 'center',
        letterSpacing: 2.5,
        textTransform: 'uppercase',
        borderTop: true,
        borderBottom: true,
        editable: true,
      },
      // ── main headline ──
      {
        id: 'headline',
        type: 'text',
        x: 20,
        y: 106,
        w: 754,
        h: 56,
        content: 'A PORTRAIT OF ELEGANCE AND CHARM\nCAPTURED IN TIMELESS PHOTOGRAPHY',
        fontSize: 26,
        fontFamily: 'Playfair Display, serif',
        fontWeight: '900',
        textAlign: 'center',
        lineHeight: 1.15,
        textTransform: 'uppercase',
        editable: true,
      },
      {
        id: 'subtitle',
        type: 'text',
        x: 80,
        y: 168,
        w: 634,
        h: 24,
        content:
          "An Exclusive Glimpse Into the Season's Most Celebrated Exhibition — Portraits That Speak Volumes",
        fontSize: 12,
        fontFamily: 'Lora, serif',
        fontStyle: 'italic',
        fontWeight: '400',
        textAlign: 'center',
        borderBottom: true,
        editable: true,
      },
      // ── hero photo + sidebar ──
      {
        id: 'photo-hero',
        type: 'image',
        x: 20,
        y: 202,
        w: 500,
        h: 310,
        placeholder: 'Hero Photo',
      },
      {
        id: 'sidebar-title',
        type: 'text',
        x: 534,
        y: 202,
        w: 240,
        h: 22,
        content: 'FROM THE EDITOR',
        fontSize: 10,
        fontFamily: 'Inter, sans-serif',
        fontWeight: '700',
        textAlign: 'left',
        letterSpacing: 2,
        textTransform: 'uppercase',
        borderBottom: true,
        editable: true,
      },
      {
        id: 'sidebar-text',
        type: 'text',
        x: 534,
        y: 230,
        w: 240,
        h: 282,
        content:
          'We are proud to present this evening\'s special feature on the art of portraiture — an ancient craft now reimagined through the lens of modern photography.\n\nThe subjects of these photographs were not professional models; they were ordinary people, captured in extraordinary moments of truth and beauty.\n\n"A great photograph is one that fully expresses what one feels, in the deepest sense, about what is being photographed," as the renowned master once wrote. This collection embodies that philosophy with quiet, powerful grace.',
        fontSize: 10,
        fontFamily: 'Lora, serif',
        fontWeight: '400',
        textAlign: 'justify',
        lineHeight: 1.65,
        editable: true,
      },
      // ── 3-column section ──
      {
        id: 'section-break',
        type: 'text',
        x: 20,
        y: 522,
        w: 754,
        h: 20,
        content: '— FEATURED COLUMNS & GALLERY —',
        fontSize: 9,
        fontFamily: 'Inter, sans-serif',
        fontWeight: '700',
        textAlign: 'center',
        letterSpacing: 4,
        textTransform: 'uppercase',
        borderTop: true,
        borderBottom: true,
        editable: true,
      },
      {
        id: 'col1-title',
        type: 'text',
        x: 20,
        y: 550,
        w: 235,
        h: 18,
        content: 'ON BEAUTY',
        fontSize: 10,
        fontFamily: 'Inter, sans-serif',
        fontWeight: '700',
        textAlign: 'left',
        letterSpacing: 2,
        textTransform: 'uppercase',
        borderBottom: true,
        editable: true,
      },
      {
        id: 'col1-text',
        type: 'text',
        x: 20,
        y: 574,
        w: 235,
        h: 200,
        content:
          'Beauty, in its truest form, is not about perfection — it is about authenticity. The most compelling portraits in this collection share one remarkable quality: an unguarded honesty that transcends the surface.\n\nThe artist behind the lens understands that real beauty emerges when the subject forgets the camera is there. It is in the unposed gesture, the natural fall of light across a thoughtful brow, that truth reveals itself.',
        fontSize: 10,
        fontFamily: 'Lora, serif',
        fontWeight: '400',
        textAlign: 'justify',
        lineHeight: 1.65,
        editable: true,
      },
      {
        id: 'col2-photo',
        type: 'image',
        x: 268,
        y: 550,
        w: 248,
        h: 224,
        placeholder: 'Photo 2',
      },
      {
        id: 'col3-title',
        type: 'text',
        x: 528,
        y: 550,
        w: 246,
        h: 18,
        content: 'ON CHARACTER',
        fontSize: 10,
        fontFamily: 'Inter, sans-serif',
        fontWeight: '700',
        textAlign: 'left',
        letterSpacing: 2,
        textTransform: 'uppercase',
        borderBottom: true,
        editable: true,
      },
      {
        id: 'col3-text',
        type: 'text',
        x: 528,
        y: 574,
        w: 246,
        h: 200,
        content:
          'Character, like good wine, reveals itself over time. The photographer has an extraordinary gift for coaxing it to the surface in a single frame — a raised eyebrow, a half-smile, a distant gaze.\n\nThese images remind us that every face carries the weight of a lifetime of experiences. To look into the eyes of these subjects is to be invited, however briefly, into the landscape of another human soul.',
        fontSize: 10,
        fontFamily: 'Lora, serif',
        fontWeight: '400',
        textAlign: 'justify',
        lineHeight: 1.65,
        editable: true,
      },
      // ── divider ──
      {
        id: 'divider-mid',
        type: 'text',
        x: 20,
        y: 784,
        w: 754,
        h: 18,
        content: '— FURTHER PORTRAITS —',
        fontSize: 9,
        fontFamily: 'Inter, sans-serif',
        fontWeight: '600',
        textAlign: 'center',
        letterSpacing: 4,
        textTransform: 'uppercase',
        borderTop: true,
        borderBottom: true,
        editable: true,
      },
      // ── bottom photos ──
      {
        id: 'photo-bottom-1',
        type: 'image',
        x: 20,
        y: 812,
        w: 365,
        h: 200,
        placeholder: 'Photo 3',
      },
      {
        id: 'photo-bottom-2',
        type: 'image',
        x: 397,
        y: 812,
        w: 377,
        h: 200,
        placeholder: 'Photo 4',
      },
      // ── bottom article ──
      {
        id: 'article-bottom',
        type: 'text',
        x: 20,
        y: 1022,
        w: 754,
        h: 66,
        content:
          'The exhibition continues through the season at the Grand Gallery, with special evening viewings on Fridays and Saturdays. Tickets may be purchased at the door or reserved in advance. A limited-edition catalogue accompanies the exhibition and is available at the gallery bookshop. All proceeds benefit the Foundation for Emerging Photographers.',
        fontSize: 10,
        fontFamily: 'Lora, serif',
        fontWeight: '400',
        textAlign: 'justify',
        lineHeight: 1.6,
        editable: true,
      },
      // ── footer ──
      {
        id: 'footer',
        type: 'text',
        x: 0,
        y: 1096,
        w: 794,
        h: 22,
        content: 'THE EVENING HERALD · LONDON · PRINTED SINCE 1842 · ALL RIGHTS RESERVED',
        fontSize: 7.5,
        fontFamily: 'Inter, sans-serif',
        fontWeight: '400',
        textAlign: 'center',
        letterSpacing: 2,
        textTransform: 'uppercase',
        borderTop: true,
        editable: true,
      },
    ],
  },

  // ═══════════════════════════════════════════════════════════
  // TEMPLATE 7: Vintage Portrait (A4 · 794×1123) — NEW
  // ═══════════════════════════════════════════════════════════
  {
    id: 'vintage-portrait-a4',
    name: 'Vintage Portrait',
    description: 'Minimalist portrait photobooth with large central photo and decorative layout',
    category: 'minimal',
    paperSize: 'A4',
    width: 794,
    height: 1123,
    background: '#F5F0E8',
    slots: [
      // ── top label ──
      {
        id: 'label-top',
        type: 'text',
        x: 0,
        y: 10,
        w: 794,
        h: 14,
        content: 'PORTRAIT STUDIO · EST. 1987 · ORIGINAL SERIES',
        fontSize: 7,
        fontFamily: 'Inter, sans-serif',
        fontWeight: '600',
        textAlign: 'center',
        letterSpacing: 4,
        textTransform: 'uppercase',
        editable: true,
      },
      // ── masthead ──
      {
        id: 'masthead',
        type: 'text',
        x: 0,
        y: 28,
        w: 794,
        h: 44,
        content: 'Vintage Portrait',
        fontSize: 38,
        fontFamily: 'Playfair Display, serif',
        fontWeight: '700',
        fontStyle: 'italic',
        textAlign: 'center',
        letterSpacing: 2,
        editable: true,
      },
      // ── dateline ──
      {
        id: 'dateline',
        type: 'text',
        x: 0,
        y: 76,
        w: 794,
        h: 18,
        content: 'NO. 12  ·  SPRING / SUMMER COLLECTION  ·  TIMELESS MOMENTS',
        fontSize: 7.5,
        fontFamily: 'Inter, sans-serif',
        fontWeight: '400',
        textAlign: 'center',
        letterSpacing: 3,
        textTransform: 'uppercase',
        borderTop: true,
        borderBottom: true,
        editable: true,
      },
      // ── hero photo ──
      {
        id: 'photo-hero',
        type: 'image',
        x: 60,
        y: 108,
        w: 674,
        h: 480,
        placeholder: 'Hero Portrait',
      },
      // ── caption + quote ──
      {
        id: 'hero-caption',
        type: 'text',
        x: 60,
        y: 596,
        w: 674,
        h: 18,
        content: 'A portrait is not made in the camera but on either side of it. — Edward Steichen',
        fontSize: 10,
        fontFamily: 'Lora, serif',
        fontStyle: 'italic',
        fontWeight: '400',
        textAlign: 'center',
        editable: true,
      },
      {
        id: 'pull-quote',
        type: 'text',
        x: 100,
        y: 622,
        w: 594,
        h: 30,
        content: 'Every face is a story waiting to be told.',
        fontSize: 18,
        fontFamily: 'Playfair Display, serif',
        fontWeight: '900',
        fontStyle: 'italic',
        textAlign: 'center',
        borderTop: true,
        borderBottom: true,
        editable: true,
      },
      // ── three-column: photo + text + photo ──
      {
        id: 'photo-left',
        type: 'image',
        x: 20,
        y: 666,
        w: 240,
        h: 180,
        placeholder: 'Photo 2',
      },
      {
        id: 'article-center',
        type: 'text',
        x: 272,
        y: 666,
        w: 250,
        h: 180,
        content:
          'We believe that every person carries within them a quiet beauty — one that shines brightest in moments of natural ease. Our studio creates a private, comfortable space where you can simply be yourself.\n\nNo posing. No pretence. Just you — captured with warmth, artistry, and a love for timeless portraiture.',
        fontSize: 10,
        fontFamily: 'Lora, serif',
        fontWeight: '400',
        textAlign: 'justify',
        lineHeight: 1.65,
        editable: true,
      },
      {
        id: 'photo-right',
        type: 'image',
        x: 534,
        y: 666,
        w: 240,
        h: 180,
        placeholder: 'Photo 3',
      },
      // ── divider ──
      {
        id: 'divider',
        type: 'text',
        x: 20,
        y: 856,
        w: 754,
        h: 18,
        content: '— THE COLLECTION —',
        fontSize: 9,
        fontFamily: 'Inter, sans-serif',
        fontWeight: '600',
        textAlign: 'center',
        letterSpacing: 5,
        textTransform: 'uppercase',
        borderTop: true,
        borderBottom: true,
        editable: true,
      },
      // ── photo strip: 4 photos ──
      {
        id: 'photo-strip-1',
        type: 'image',
        x: 20,
        y: 884,
        w: 180,
        h: 140,
        placeholder: 'Photo 4',
      },
      {
        id: 'photo-strip-2',
        type: 'image',
        x: 208,
        y: 884,
        w: 180,
        h: 140,
        placeholder: 'Photo 5',
      },
      {
        id: 'photo-strip-3',
        type: 'image',
        x: 396,
        y: 884,
        w: 180,
        h: 140,
        placeholder: 'Photo 6',
      },
      {
        id: 'photo-strip-4',
        type: 'image',
        x: 584,
        y: 884,
        w: 190,
        h: 140,
        placeholder: 'Photo 7',
      },
      // ── credits ──
      {
        id: 'credits',
        type: 'text',
        x: 20,
        y: 1034,
        w: 754,
        h: 52,
        content:
          'Photography by Studio · Art Direction by Creative Lab · Styling by Atelier\nSpecial thanks to all who shared their stories and their smiles.\nBook your session today — every portrait is a celebration of who you are.',
        fontSize: 10,
        fontFamily: 'Lora, serif',
        fontWeight: '400',
        textAlign: 'center',
        lineHeight: 1.6,
        editable: true,
      },
      // ── footer ──
      {
        id: 'footer',
        type: 'text',
        x: 0,
        y: 1096,
        w: 794,
        h: 22,
        content: 'VINTAGE PORTRAIT STUDIO · EST. 1987 · ALL RIGHTS RESERVED',
        fontSize: 7.5,
        fontFamily: 'Inter, sans-serif',
        fontWeight: '400',
        textAlign: 'center',
        letterSpacing: 2,
        textTransform: 'uppercase',
        borderTop: true,
        editable: true,
      },
    ],
  },

  // ═══════════════════════════════════════════════════════════
  // TEMPLATE 8: The Continental Review (A3 · 1123×1587) — NEW
  // ═══════════════════════════════════════════════════════════
  {
    id: 'continental-review-a3',
    name: 'The Continental Review',
    description: 'Large format broadsheet with hero image and multi-column editorial',
    category: 'newspaper',
    paperSize: 'A3',
    width: 1123,
    height: 1587,
    background: '#FAF8F3',
    slots: [
      // ── meta bar ──
      {
        id: 'meta-left',
        type: 'text',
        x: 30,
        y: 10,
        w: 350,
        h: 16,
        content: 'THE CONTINENTAL REVIEW · SPECIAL SUPPLEMENT',
        fontSize: 8,
        fontFamily: 'Inter, sans-serif',
        fontWeight: '600',
        textAlign: 'left',
        letterSpacing: 2,
        textTransform: 'uppercase',
        editable: true,
      },
      {
        id: 'meta-right',
        type: 'text',
        x: 750,
        y: 10,
        w: 343,
        h: 16,
        content: 'SPRING / SUMMER · NO. 47 · MMXXVI',
        fontSize: 8,
        fontFamily: 'Inter, sans-serif',
        fontWeight: '400',
        textAlign: 'right',
        letterSpacing: 2,
        textTransform: 'uppercase',
        editable: true,
      },
      // ── masthead ──
      {
        id: 'masthead',
        type: 'text',
        x: 0,
        y: 28,
        w: 1123,
        h: 70,
        content: 'THE CONTINENTAL REVIEW',
        fontSize: 56,
        fontFamily: 'Playfair Display, serif',
        fontWeight: '900',
        textAlign: 'center',
        letterSpacing: 6,
        textTransform: 'uppercase',
        borderBottom: true,
        editable: true,
      },
      // ── dateline ──
      {
        id: 'dateline',
        type: 'text',
        x: 0,
        y: 100,
        w: 1123,
        h: 24,
        content:
          'PARIS · LONDON · BERLIN · ROME · MADRID  ·  A SURVEY OF ARTS, LETTERS & SOCIETY  ·  PUBLISHED QUARTERLY',
        fontSize: 9,
        fontFamily: 'Inter, sans-serif',
        fontWeight: '400',
        textAlign: 'center',
        letterSpacing: 3,
        textTransform: 'uppercase',
        borderBottom: true,
        editable: true,
      },
      // ── headline ──
      {
        id: 'headline',
        type: 'text',
        x: 30,
        y: 132,
        w: 1063,
        h: 80,
        content: 'THE NEW FACE OF EUROPEAN\nPORTRAITURE AND VISUAL ARTS',
        fontSize: 44,
        fontFamily: 'Playfair Display, serif',
        fontWeight: '900',
        textAlign: 'center',
        lineHeight: 1.12,
        textTransform: 'uppercase',
        editable: true,
      },
      // ── subtitle ──
      {
        id: 'subtitle',
        type: 'text',
        x: 120,
        y: 220,
        w: 883,
        h: 26,
        content:
          'A Comprehensive Survey of the Artists, Studios, and Movements Redefining Contemporary Photographic Practice Across the Continent',
        fontSize: 13,
        fontFamily: 'Lora, serif',
        fontStyle: 'italic',
        fontWeight: '400',
        textAlign: 'center',
        borderBottom: true,
        editable: true,
      },
      // ── byline ──
      {
        id: 'byline',
        type: 'text',
        x: 30,
        y: 254,
        w: 1063,
        h: 18,
        content:
          'By Our Arts Correspondent  ·  Photography by Various Contributors  ·  Published March 2026',
        fontSize: 9,
        fontFamily: 'Inter, sans-serif',
        fontWeight: '400',
        textAlign: 'center',
        letterSpacing: 1.5,
        textTransform: 'uppercase',
        editable: true,
      },
      // ── hero photo + sidebar ──
      {
        id: 'photo-hero',
        type: 'image',
        x: 30,
        y: 280,
        w: 700,
        h: 420,
        placeholder: 'Hero Photo',
      },
      {
        id: 'sidebar-label',
        type: 'text',
        x: 746,
        y: 280,
        w: 347,
        h: 22,
        content: 'EDITORIAL NOTE',
        fontSize: 10,
        fontFamily: 'Inter, sans-serif',
        fontWeight: '700',
        textAlign: 'left',
        letterSpacing: 3,
        textTransform: 'uppercase',
        borderBottom: true,
        editable: true,
      },
      {
        id: 'sidebar-text',
        type: 'text',
        x: 746,
        y: 308,
        w: 347,
        h: 392,
        content:
          'In an age of instant images and ephemeral digital captures, there remains a profound hunger for photographs that endure — images crafted with patience, vision, and an unwavering commitment to the art of seeing.\n\nThis special supplement brings together the finest work from studios across five nations, each contributing a unique perspective to the ongoing conversation about what it means to make a portrait in the twenty-first century.\n\nThe artists featured here share a common belief: that photography, at its best, is not merely a record of appearance, but a revelation of character. Their work invites us to slow down, to truly look, and perhaps to see ourselves anew.\n\nWe hope these pages inspire you to seek beauty in the everyday, to cherish the fleeting moment, and to remember that every face tells a story worth preserving for generations to come.',
        fontSize: 11,
        fontFamily: 'Lora, serif',
        fontWeight: '400',
        textAlign: 'justify',
        lineHeight: 1.65,
        editable: true,
      },
      // ── section break ──
      {
        id: 'section-break',
        type: 'text',
        x: 30,
        y: 712,
        w: 1063,
        h: 24,
        content: '— SELECTED WORKS FROM THE COLLECTION —',
        fontSize: 11,
        fontFamily: 'Inter, sans-serif',
        fontWeight: '700',
        textAlign: 'center',
        letterSpacing: 5,
        textTransform: 'uppercase',
        borderTop: true,
        borderBottom: true,
        editable: true,
      },
      // ── 3 photos row ──
      {
        id: 'photo-2',
        type: 'image',
        x: 30,
        y: 746,
        w: 344,
        h: 260,
        placeholder: 'Photo 2',
      },
      {
        id: 'photo-3',
        type: 'image',
        x: 386,
        y: 746,
        w: 344,
        h: 260,
        placeholder: 'Photo 3',
      },
      {
        id: 'photo-4',
        type: 'image',
        x: 742,
        y: 746,
        w: 351,
        h: 260,
        placeholder: 'Photo 4',
      },
      // ── captions ──
      {
        id: 'cap-2',
        type: 'text',
        x: 30,
        y: 1010,
        w: 344,
        h: 18,
        content: 'I — Study in Natural Light',
        fontSize: 9,
        fontFamily: 'Inter, sans-serif',
        fontStyle: 'italic',
        textAlign: 'center',
        editable: true,
      },
      {
        id: 'cap-3',
        type: 'text',
        x: 386,
        y: 1010,
        w: 344,
        h: 18,
        content: 'II — The Quiet Hour',
        fontSize: 9,
        fontFamily: 'Inter, sans-serif',
        fontStyle: 'italic',
        textAlign: 'center',
        editable: true,
      },
      {
        id: 'cap-4',
        type: 'text',
        x: 742,
        y: 1010,
        w: 351,
        h: 18,
        content: 'III — Reflections on Identity',
        fontSize: 9,
        fontFamily: 'Inter, sans-serif',
        fontStyle: 'italic',
        textAlign: 'center',
        editable: true,
      },
      // ── 3-column article ──
      {
        id: 'article-label',
        type: 'text',
        x: 30,
        y: 1038,
        w: 1063,
        h: 20,
        content: 'ACROSS THE CONTINENT — NOTES ON THE STATE OF PORTRAITURE',
        fontSize: 10,
        fontFamily: 'Inter, sans-serif',
        fontWeight: '700',
        textAlign: 'center',
        letterSpacing: 3,
        textTransform: 'uppercase',
        borderBottom: true,
        editable: true,
      },
      {
        id: 'article-col1',
        type: 'text',
        x: 30,
        y: 1066,
        w: 340,
        h: 170,
        content:
          'In Paris, a new generation of portrait photographers is drawing inspiration from the classical masters while embracing digital innovation. Studios along the Left Bank have become gathering places for artists seeking to bridge tradition and modernity.\n\nThe French approach to portraiture has always been marked by an emphasis on atmosphere and emotion — qualities that remain at the heart of the discipline today.',
        fontSize: 11,
        fontFamily: 'Lora, serif',
        fontWeight: '400',
        textAlign: 'justify',
        lineHeight: 1.65,
        editable: true,
      },
      {
        id: 'article-col2',
        type: 'text',
        x: 386,
        y: 1066,
        w: 340,
        h: 170,
        content:
          "London's portrait studios have long been regarded as among the finest in the world. From the grand institutions of Mayfair to the independent spaces of East London, the city offers an unparalleled diversity of styles and perspectives.\n\nBritish portraiture tends toward the understated — a tradition of quiet observation and subtle revelation that has influenced photographers worldwide for generations.",
        fontSize: 11,
        fontFamily: 'Lora, serif',
        fontWeight: '400',
        textAlign: 'justify',
        lineHeight: 1.65,
        editable: true,
      },
      {
        id: 'article-col3',
        type: 'text',
        x: 742,
        y: 1066,
        w: 351,
        h: 170,
        content:
          'Berlin, with its rich artistic heritage and spirit of reinvention, has emerged as a vital centre for experimental portraiture. Studios in Kreuzberg and Mitte are pushing boundaries with bold new techniques and unconventional subjects.\n\nThe German school brings a rigorous, conceptual approach to the portrait — treating each image as both a document and a work of art in its own right.',
        fontSize: 11,
        fontFamily: 'Lora, serif',
        fontWeight: '400',
        textAlign: 'justify',
        lineHeight: 1.65,
        editable: true,
      },
      // ── pull quote ──
      {
        id: 'pull-quote',
        type: 'text',
        x: 30,
        y: 1244,
        w: 1063,
        h: 26,
        content:
          '"The camera is an instrument that teaches people how to see without a camera." — Dorothea Lange',
        fontSize: 13,
        fontFamily: 'Lora, serif',
        fontStyle: 'italic',
        fontWeight: '700',
        textAlign: 'center',
        borderTop: true,
        borderBottom: true,
        editable: true,
      },
      // ── bottom photos ──
      {
        id: 'photo-5',
        type: 'image',
        x: 30,
        y: 1280,
        w: 530,
        h: 260,
        placeholder: 'Photo 5',
      },
      {
        id: 'photo-6',
        type: 'image',
        x: 580,
        y: 1280,
        w: 513,
        h: 260,
        placeholder: 'Photo 6',
      },
      // ── footer ──
      {
        id: 'footer',
        type: 'text',
        x: 0,
        y: 1556,
        w: 1123,
        h: 24,
        content:
          '© THE CONTINENTAL REVIEW · PARIS · LONDON · BERLIN · PUBLISHED QUARTERLY · ALL RIGHTS RESERVED',
        fontSize: 8,
        fontFamily: 'Inter, sans-serif',
        fontWeight: '400',
        textAlign: 'center',
        letterSpacing: 3,
        textTransform: 'uppercase',
        borderTop: true,
        editable: true,
      },
    ],
  },
]

export function getTemplatesBySize(size: 'A4' | 'A3'): NewspaperTemplate[] {
  return templates.filter((t) => t.paperSize === size)
}

export function getTemplateById(id: string): NewspaperTemplate | undefined {
  return templates.find((t) => t.id === id)
}
